
export default new Map([
["src/content/blog/english/apt-detection-ai-response.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fenglish%2Fapt-detection-ai-response.mdx&astroContentModuleFlag=true")],
["src/content/blog/english/mitre-attack-guide.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fenglish%2Fmitre-attack-guide.mdx&astroContentModuleFlag=true")],
["src/content/blog/english/owasp-top-10-ai-security.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fenglish%2Fowasp-top-10-ai-security.mdx&astroContentModuleFlag=true")],
["src/content/integration/english/digitalocean.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fintegration%2Fenglish%2Fdigitalocean.mdx&astroContentModuleFlag=true")],
["src/content/integration/english/aws-security-hub.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fintegration%2Fenglish%2Faws-security-hub.mdx&astroContentModuleFlag=true")],
["src/content/integration/english/email.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fintegration%2Fenglish%2Femail.mdx&astroContentModuleFlag=true")],
["src/content/integration/english/discord.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fintegration%2Fenglish%2Fdiscord.mdx&astroContentModuleFlag=true")],
["src/content/integration/english/github.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fintegration%2Fenglish%2Fgithub.mdx&astroContentModuleFlag=true")],
["src/content/integration/english/azure.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fintegration%2Fenglish%2Fazure.mdx&astroContentModuleFlag=true")],
["src/content/integration/english/google-cloud.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fintegration%2Fenglish%2Fgoogle-cloud.mdx&astroContentModuleFlag=true")],
["src/content/integration/english/gitlab.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fintegration%2Fenglish%2Fgitlab.mdx&astroContentModuleFlag=true")],
["src/content/integration/english/jira.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fintegration%2Fenglish%2Fjira.mdx&astroContentModuleFlag=true")],
["src/content/integration/english/microsoft-teams.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fintegration%2Fenglish%2Fmicrosoft-teams.mdx&astroContentModuleFlag=true")],
["src/content/integration/english/servicenow.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fintegration%2Fenglish%2Fservicenow.mdx&astroContentModuleFlag=true")],
["src/content/integration/english/pagerduty.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fintegration%2Fenglish%2Fpagerduty.mdx&astroContentModuleFlag=true")],
["src/content/integration/english/slack.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fintegration%2Fenglish%2Fslack.mdx&astroContentModuleFlag=true")],
["src/content/integration/english/splunk.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fintegration%2Fenglish%2Fsplunk.mdx&astroContentModuleFlag=true")]]);
		